image: docker
services:
  - docker:dind

variables:
  GITLAB_SHARED_DIND_DIR: /builds/$CI_PROJECT_PATH/shared

stages:
  - build

build:
  stage: build
  script:
    - ls -l
    - pwd
    - apk add bash
    - mkdir -p "$GITLAB_SHARED_DIND_DIR" && chmod 777 "$GITLAB_SHARED_DIND_DIR"
    - echo "Build Ubuntu 18 on all branches"
    - bash builder/build-distro ubuntu bionic
    - if echo "$CI_COMMIT_BRANCH" | grep -Eq '(release|testing)'; then
        echo "Build all distros";
        bash builder/build-distro ubuntu focal;
        bash builder/build-distro debian buster;
        bash builder/build-distro debian bullseye;
        bash builder/build-distro kali kali-rolling;
      fi
    - mkdir output
    - cp -r builder/build/* output/
    - rm output/*.tar.gz
  artifacts:
    paths:
      - output/
