image: docker
services:
  - docker:dind

variables:
  GITLAB_SHARED_DIND_DIR: /builds/$CI_PROJECT_PATH/shared

stages:
  - build

.prepare_build: &prepare_build
  - ls -l
  - pwd
  - apk add bash
  - mkdir -p "$GITLAB_SHARED_DIND_DIR" && chmod 777 "$GITLAB_SHARED_DIND_DIR"

.prepare_artfacts: &prepare_artfacts
  - mkdir output
  - cp -r builder/build/* output/
  - rm output/*.tar.gz

build_deb:
  stage: build
  before_script:
    - *prepare_build
  after_script:
    - *prepare_artfacts
  script:
    - echo "Always build Ubuntu 18"
    - bash builder/build-distro ubuntu bionic
    - if echo "$CI_COMMIT_BRANCH" | grep -Eq '(release|testing)'; then
        echo "Build all distros";
        bash builder/build-distro ubuntu focal;
        bash builder/build-distro debian buster;
        bash builder/build-distro debian bullseye;
        bash builder/build-distro kali kali-rolling;
      fi
  artifacts:
    paths:
      - output/
